### PR TITLE
Encoding and print statements are fixed to provide python3 compatibility

### LINKED ISSUE #1: Add compatiblity for python3

### PR DESCRIPTION
**Pull request by mdogan93**
Resolves #1 
Encoding and print statements based conflicts are resolved.

### CODE REVIEW

**Comment by D-Nice** [comment]
Thanks for this contribution @mdogan93 

We have someone looking over this :)

I did just a quick edit to your PR message body, so it auto-closes issue #1 on merge, hope you don't mind.

**Review by gitmp01 — CHANGES_REQUESTED** [review]
Hello @mdogan93, 
firstly thank you for your help. Would you please move this changes to another file called `encrypted_queries_tools-p3.py` and keep the previous version as it was? So the current script should still work with python2 when users pull from the repo.

**Comment by mdogan93** [comment]
Thanks for your review, I have modified file name.

**Comment by gitmp01** [comment]
Hi @mdogan93,
maybe there was a misunderstanding as we would like to keep a copy of the python2 version as well :sweat_smile: Apologies, never mind tough, we will merge the changes and add the old file later. 

Thank you again!:muscle:

**Review by gitmp01 — APPROVED** [review]

**Pull request merged**
